version: '3.0'

services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
     - "8080:8080"
    volumes:
     - ./service-discovery:/app
     - ~/.m2:/root/.m2
    networks:
     - app-network
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
     - "8084:8080"
    volumes:
     - ./auth-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network
  financial-service:
    build:
      context: ./financial-service
    container_name: financial-service
    ports:
      - "8085:8080"
    volumes:
      - ./financial-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - service-discovery
      - auth-service
    networks:
      - app-network
  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "8085:8080"
    volumes:
      - ./inventory-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - service-discovery
      - auth-service
    networks:
      - app-network
  sales-service:
    build:
      context: ./sales-service
    container_name: sales-service
    ports:
      - "8086:8080"
    volumes:
      - ./sales-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - service-discovery
      - auth-service
      - inventory-service
    networks:
      - app-network
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
     - "8083:8080"
    volumes:
     - ./gateway-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network
networks:
  app-network:
    driver: bridge
